# Generated by Django 6.0.2 on 2026-03-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AddField(
            model_name='person',
            name='citizen_id',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='0000000000000', max_length=50),
            preserve_default=False,
        ),
    ]
